# -*- coding: utf-8 -*-
"""Assignment 23.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13otmQVLGgmEFdjT870UIYQaNDdMNjbz6
"""

# Importing required libraries
import time
import matplotlib.pyplot as plt


# Part 1: Time Complexity Classification

# Part 2: Binary Search + Fibonacci Comparison


# Binary search implementation — classic divide and conquer
def binary_search(arr, target):
    """
    Simple binary search function.
    Time complexity: Θ(log n) since the array is halved each step.
    """
    left, right = 0, len(arr) - 1
    while left <= right:
        mid = (left + right) // 2
        if arr[mid] == target:
            return mid
        elif arr[mid] < target:
            left = mid + 1
        else:
            right = mid - 1
    return -1

# Trying binary search on a test list
arr = list(range(0, 100, 2))  # [0, 2, 4, ..., 98]
target = 42
result = binary_search(arr, target)
print(f"Binary Search: Target {target} found at index {result}")


# Fibonacci Functions: Recursive vs Iterative


# Recursive version (inefficient)
def fib_recur(n):
    if n <= 1:
        return n
    return fib_recur(n - 1) + fib_recur(n - 2)

# Iterative version (efficient)
def fib_iter(n):
    a, b = 0, 1
    for _ in range(n):
        a, b = b, a + b
    return a


# Comparing runtimes for both methods


n_values = list(range(10, 41))  # Using n = 10 to 40
recur_times = []
iter_times = []

print("Running time comparison between recursive and iterative Fibonacci...")

for n in n_values:
    # Time recursive
    start = time.time()
    fib_recur(n)
    recur_times.append(time.time() - start)

    # Time iterative
    start = time.time()
    fib_iter(n)
    iter_times.append(time.time() - start)

# Plotting the results
plt.figure(figsize=(10, 6))
plt.plot(n_values, recur_times, label='Recursive Fibonacci', color='red', marker='o')
plt.plot(n_values, iter_times, label='Iterative Fibonacci', color='green', marker='s')
plt.title('Fibonacci Runtime Comparison (Recursive vs Iterative)')
plt.xlabel('n')
plt.ylabel('Time (seconds)')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

